#! /usr/bin/env node

import chalk from 'chalk'
import yargs from 'yargs'

import { defaultLangOptions } from './lang'

import init, { defaultOptions } from '.'

const argv = yargs(process.argv.slice(2))
  .options({
    change: {
      alias: 'c',
      type: 'boolean',
      describe:
        'Should program preform source changes ' +
        'to DefaultQuests.json. If --no-change is set, ' +
        'only keys sorting would be performed',
      default: defaultOptions.change,
    },
    quests: {
      alias: 'q',
      type: 'string',
      describe:
        'Path to file DefaultQuests.json, ' +
        'generated by Better Questing mod',
      default: defaultOptions.quests,
    },
    complete: {
      alias: 'e',
      type: 'string',
      describe:
        'Name of quest that would require all other ' +
        'quests in this chapter as requirement',
      default: defaultOptions.complete,
    },
    output: {
      alias: 'o',
      type: 'string',
      describe: 'Output directory path for splitted JSONs',
      default: defaultOptions.output,
    },
    langPath: {
      alias: 'p',
      type: 'string',
      describe: 'Directory with lang files, like "en_us.lang"',
      default: defaultLangOptions.langPath,
    },
    langPrefix: {
      alias: 'x',
      type: 'string',
      describe: 'Prefix that would be added to lang codes',
      default: defaultLangOptions.langPrefix,
    },
  })
  .version(false)
  .wrap(null)
  .parseSync()

const log = {
  info: (s: any) => process.stdout.write(chalk.gray(s)),
  err: (s: any) => process.stdout.write(chalk.red(s)),
}

;(async () => {
  await init(argv, log)
})()
